### ISSUE TITLE
404 in admin dashboard after login

### ISSUE THREAD

**Issue by buccalon** [imaginerio/narratives#65]
![image](https://user-images.githubusercontent.com/476699/136711978-8877384c-6b57-44ea-b853-0e03c81cb6c8.png)

**Comment by davidheyman** [comment]
@buccalon This is fixed and tested on a private browsing window. Can you confirm that it works for you as well?

**Comment by buccalon** [comment]
Thanks! Now I can access the panel, but #61 still persists when I try to add a narrative to the galley:

![image](https://user-images.githubusercontent.com/476699/136794880-df783623-9ea4-4e38-adaf-e7ef7080a7ce.png)
